// 12x12 sprites, one character per pixel, drawn the same way as the favicon.
// a space is transparent; every other character is a key in PALETTE below.

export const PALETTE: Record<string, string> = {
  k: '#4a3a40', // outline
  w: '#ffffff',
  g: '#a3a1aa',
  n: '#5c7ba8', // nautical blue
  b: '#8fb3e8',
  r: '#c0667f', // site accent
  p: '#f29bb2', // favicon pink
  c: '#e79bb0',
  y: '#e8c46e',
  e: '#9fd3b3',
}

export const sprites = {
  ship: [
    '            ',
    '     rr     ',
    '     rr     ',
    '   gggggg   ',
    '  gggggggg  ',
    '  wwwwwwww  ',
    ' nnnnnnnnnn ',
    ' nnnnnnnnnn ',
    '  nnnnnnnn  ',
    '   nnnnnn   ',
    '            ',
    ' bb  bb  bb ',
  ],
  anchor: [
    '            ',
    '    nnnn    ',
    '    n  n    ',
    '    nnnn    ',
    '  nnnnnnnn  ',
    '     nn     ',
    '     nn     ',
    '  n  nn  n  ',
    '  n  nn  n  ',
    '  nn nn nn  ',
    '   nnnnnn   ',
    '            ',
  ],
  syringe: [
    '    kkkkk   ',
    '      k     ',
    '      k     ',
    '    kkkkk   ',
    '    kwwwk   ',
    '    kwwwk   ',
    '    kpppk   ',
    '    kpppk   ',
    '    kkkkk   ',
    '      k     ',
    '      k     ',
    '      k     ',
  ],
  qr: [
    '            ',
    ' kkk    kkk ',
    ' k k  k k k ',
    ' kkk k  kkk ',
    '     k k    ',
    ' k k  kk  k ',
    '   kk  k kk ',
    ' k  k kk  k ',
    ' kkk  k  kk ',
    ' k k kk k k ',
    ' kkk  k kk  ',
    '            ',
  ],
  folder: [
    '            ',
    '            ',
    '  kkkk      ',
    '  kyykkkkkk ',
    '  kyyyyyyyk ',
    '  kywwwwwyk ',
    '  kywwwwwyk ',
    '  kyyyyyyyk ',
    '  kyyyyyyyk ',
    '  kkkkkkkkk ',
    '            ',
    '            ',
  ],
  envelope: [
    '            ',
    '            ',
    ' kkkkkkkkkk ',
    ' kppppppppk ',
    ' kwppppppwk ',
    ' kwwppppwwk ',
    ' kwwwppwwwk ',
    ' kwwwwwwwwk ',
    ' kwwwwwwwwk ',
    ' kkkkkkkkkk ',
    '            ',
    '            ',
  ],
  flower: [
    '            ',
    '    cccc    ',
    '   cccccc   ',
    '   cccccc   ',
    ' cccccccccc ',
    ' cccyyyyccc ',
    ' cccyyyyccc ',
    ' cccccccccc ',
    '   cccccc   ',
    '   cccccc   ',
    '    cccc    ',
    '            ',
  ],
} satisfies Record<string, string[]>

export type SpriteName = keyof typeof sprites
